#!/bin/bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
    >&2 echo "USAGE: ./beam [SCRIPT_NAME]"
    >&2 echo "Sample: ./beam basic.py"
    exit 1
fi

readonly script=/opt/beam/$1
readonly local_data=`cd "../data"; pwd`
docker run --rm -v "${PWD}":/opt/beam -v "${local_data}":/data -ti luisbelloch/beam python ${script} ${@:2}

